<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <NoWarn>1701;1702;1591;CS8618;NU1701;</NoWarn>
    <IsPackable>false</IsPackable>
    <RootNamespace>Cross.PepperVault.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />

    <PackageReference Include="Bogus" Version="35.6.1" />
    <PackageReference Include="FluentAssertions" Version="6.12.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="coverlet.msbuild" Version="6.0.2" />
    <PackageReference Include="opencover" Version="4.7.1221" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" Condition="'$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'net7.0' Or '$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.14" Condition="'$(TargetFramework)' == 'net9.0'" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" Condition="'$(TargetFramework)' == 'net10.0'" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" Condition="'$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'net7.0' Or '$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.14" Condition="'$(TargetFramework)' == 'net9.0'" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" Condition="'$(TargetFramework)' == 'net10.0'" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" Condition="'$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'net7.0' Or '$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.14" Condition="'$(TargetFramework)' == 'net9.0'" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" Condition="'$(TargetFramework)' == 'net10.0'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cross.PepperVault\Cross.PepperVault.csproj" />
    <ProjectReference Include="..\Cross.PepperVault.AwsSecretsJson\Cross.PepperVault.AwsSecretsJson.csproj" />
    <ProjectReference Include="..\Cross.PepperVault.AzureKvJson\Cross.PepperVault.AzureKvJson.csproj" />
    <ProjectReference Include="..\Cross.PepperVault.AzureKvVersioned\Cross.PepperVault.AzureKvVersioned.csproj" />
    <ProjectReference Include="..\Cross.PepperVault.Env\Cross.PepperVault.Env.csproj" />
    <ProjectReference Include="..\Cross.PepperVault.EnvJson\Cross.PepperVault.EnvJson.csproj" />
    <ProjectReference Include="..\Cross.PepperVault.FileJson\Cross.PepperVault.FileJson.csproj" />
    <ProjectReference Include="..\Cross.PepperVault.GcpSecretManagerJson\Cross.PepperVault.GcpSecretManagerJson.csproj" />
    <ProjectReference Include="..\Cross.PepperVault.HcvKv2Json\Cross.PepperVault.HcvKv2Json.csproj" />
  </ItemGroup>

</Project>
