<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <NoWarn>1701;1702;1591;CS8618;</NoWarn>
    <RootNamespace>Cross.PepperVault</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cross.PepperVault\Cross.PepperVault.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VaultSharp" Version="1.17.5.1" />
  </ItemGroup>

</Project>
